import type { User, Bet, UserBet } from "./types"

export const mockUsers: User[] = [
  {
    id: "user-1",
    name: "Alice",
    handle: "Alice",
    avatar: "/woman-profile-photo.png",
    balance: 1500,
  },
  {
    id: "user-2",
    name: "Bob",
    handle: "Bob",
    avatar: "/man-profile.png",
    balance: 2500,
  },
  {
    id: "user-3",
    name: "Charlie",
    handle: "Charlie",
    avatar: "/man-profile.png",
    balance: 800,
  },
  {
    id: "user-4",
    name: "Diana",
    handle: "Diana",
    avatar: "/woman-profile-photo.png",
    balance: 3200,
  },
  {
    id: "user-5",
    name: "Ethan",
    handle: "Ethan",
    avatar: "/man-profile.png",
    balance: 1200,
  },
  {
    id: "user-6",
    name: "Fiona",
    handle: "Fiona",
    avatar: "/woman-profile-photo.png",
    balance: 1800,
  },
]

export const mockJudges: User[] = [
  {
    id: "judge-1",
    name: "Samuel",
    handle: "Samuel",
    avatar: "/man-profile.png",
  },
  {
    id: "judge-2",
    name: "Rebecca",
    handle: "Rebecca",
    avatar: "/woman-profile-photo.png",
  },
  {
    id: "judge-3",
    name: "Marcus",
    handle: "Marcus",
    avatar: "/crypto-trader-profile-photo.jpg",
  },
]

export const mockBets: Bet[] = [
  {
    id: "bet-1",
    title: "Will Bitcoin reach $100k by end of 2025?",
    description: "Resolves YES if Bitcoin price reaches $100,000 USD on any major exchange",
    creator: { id: "creator-1", name: "Alex", handle: "Alex", avatar: "/crypto-trader-profile-photo.jpg" },
    image: "/bitcoin-chart-with-growth-trend.jpg",
    currency: "USD",
    bettingEndsAt: new Date(Date.now() + 7 * 86400000).toISOString(),
    resolutionDate: new Date(Date.now() + 40 * 86400000).toISOString(),
    yesBets: [
      { userId: "user-1", amount: 150 },
      { userId: "user-2", amount: 200 },
      { userId: "user-5", amount: 100 },
    ],
    noBets: [
      { userId: "user-3", amount: 50 },
      { userId: "user-4", amount: 75 },
    ],
    createdAt: new Date().toISOString(),
    judges: [mockJudges[0], mockJudges[1]],
  },
  {
    id: "bet-2",
    title: "Will Taylor Swift win a Grammy in 2025?",
    description: "Resolves YES if Taylor Swift wins any Grammy award in 2025",
    creator: { id: "creator-2", name: "Sarah", handle: "Sarah", avatar: "/music-enthusiast-profile.jpg" },
    image: "/music-award-stage-with-spotlights.jpg",
    currency: "USD",
    bettingEndsAt: new Date(Date.now() + 5 * 86400000).toISOString(),
    resolutionDate: new Date(Date.now() + 35 * 86400000).toISOString(),
    yesBets: [
      { userId: "user-1", amount: 300 },
      { userId: "user-3", amount: 250 },
      { userId: "user-6", amount: 180 },
      { userId: "user-2", amount: 220 },
    ],
    noBets: [{ userId: "user-4", amount: 90 }],
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    judges: [mockJudges[1], mockJudges[2]],
  },
  {
    id: "bet-3",
    title: "Will SpaceX land humans on Mars by 2030?",
    description: "Resolves YES if humans successfully land on Mars and return safely",
    creator: { id: "creator-3", name: "David", handle: "David", avatar: "/space-enthusiast-astronomer.jpg" },
    image: "/mars-landing-spacecraft.jpg",
    currency: "USD",
    bettingEndsAt: new Date(Date.now() + 10 * 86400000).toISOString(),
    resolutionDate: new Date(Date.now() + 45 * 86400000).toISOString(),
    yesBets: [{ userId: "user-5", amount: 120 }],
    noBets: [
      { userId: "user-1", amount: 200 },
      { userId: "user-2", amount: 150 },
      { userId: "user-3", amount: 175 },
      { userId: "user-4", amount: 100 },
      { userId: "user-6", amount: 225 },
    ],
    createdAt: new Date(Date.now() - 172800000).toISOString(),
    judges: [mockJudges[0], mockJudges[2]],
  },
  {
    id: "bet-4",
    title: "Will Apple release Vision Pro 2 in 2025?",
    description: "Resolves YES if Apple announces or releases Vision Pro Gen 2",
    creator: { id: "creator-4", name: "Michael", handle: "Michael", avatar: "/tech-expert-portrait.jpg" },
    image: "/futuristic-vr-headset-technology.jpg",
    currency: "USD",
    bettingEndsAt: new Date(Date.now() + 6 * 86400000).toISOString(),
    resolutionDate: new Date(Date.now() + 30 * 86400000).toISOString(),
    yesBets: [
      { userId: "user-2", amount: 140 },
      { userId: "user-6", amount: 160 },
    ],
    noBets: [
      { userId: "user-3", amount: 110 },
      { userId: "user-4", amount: 95 },
      { userId: "user-5", amount: 130 },
    ],
    createdAt: new Date(Date.now() - 259200000).toISOString(),
    judges: mockJudges,
  },
  {
    id: "bet-5",
    title: "Will Ethereum reach $5,000 by Q2 2025?",
    description: "Resolves YES if ETH price hits $5,000 on any major exchange",
    creator: {
      id: "user-1",
      name: "Alice",
      handle: "Alice",
      avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=user1",
    },
    image: "/bitcoin-chart-with-growth-trend.jpg",
    currency: "USD",
    bettingEndsAt: new Date(Date.now() + 14 * 86400000).toISOString(),
    resolutionDate: new Date(Date.now() + 60 * 86400000).toISOString(),
    yesBets: [
      { userId: "user-2", amount: 280 },
      { userId: "user-5", amount: 190 },
    ],
    noBets: [{ userId: "user-3", amount: 85 }],
    createdAt: new Date(Date.now() - 172800000).toISOString(),
    resolved: false,
    judges: [mockJudges[0], mockJudges[1]],
  },
  {
    id: "bet-6",
    title: "Will Arsenal win the Premier League 2025?",
    description: "Resolves YES if Arsenal wins the Premier League championship",
    creator: {
      id: "user-1",
      name: "Alice",
      handle: "Alice",
      avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=user1",
    },
    image: "/mars-landing-spacecraft.jpg",
    currency: "USD",
    bettingEndsAt: new Date(Date.now() + 21 * 86400000).toISOString(),
    resolutionDate: new Date(Date.now() + 90 * 86400000).toISOString(),
    yesBets: [
      { userId: "user-1", amount: 210 },
      { userId: "user-4", amount: 165 },
      { userId: "user-6", amount: 195 },
    ],
    noBets: [
      { userId: "user-2", amount: 140 },
      { userId: "user-5", amount: 125 },
    ],
    createdAt: new Date(Date.now() - 432000000).toISOString(),
    resolved: false,
    judges: [mockJudges[1]],
  },
  {
    id: "bet-7",
    title: "Will Bitcoin crash below $50k in 2025?",
    description: "Resolves YES if BTC falls below $50,000",
    creator: {
      id: "user-1",
      name: "Alice",
      handle: "Alice",
      avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=user1",
    },
    image: "/bitcoin-chart-with-growth-trend.jpg",
    currency: "USD",
    bettingEndsAt: new Date(Date.now() - 86400000).toISOString(),
    resolutionDate: new Date(Date.now() + 30 * 86400000).toISOString(),
    yesBets: [{ userId: "user-3", amount: 105 }],
    noBets: [
      { userId: "user-2", amount: 170 },
      { userId: "user-4", amount: 145 },
      { userId: "user-5", amount: 185 },
      { userId: "user-6", amount: 200 },
    ],
    createdAt: new Date(Date.now() - 864000000).toISOString(),
    resolved: true,
    resolution: "no",
    judges: [mockJudges[0], mockJudges[2]],
  },
]

export const mockUserBets: UserBet[] = [
  {
    betId: "bet-1",
    userId: "current-user",
    prediction: "yes",
    amount: 50,
    placedAt: new Date(Date.now() - 86400000).toISOString(),
    resolved: false,
    won: undefined,
  },
  {
    betId: "bet-2",
    userId: "current-user",
    prediction: "yes",
    amount: 100,
    placedAt: new Date(Date.now() - 172800000).toISOString(),
    resolved: true,
    won: true,
  },
  {
    betId: "bet-3",
    userId: "current-user",
    prediction: "no",
    amount: 75,
    placedAt: new Date(Date.now() - 259200000).toISOString(),
    resolved: true,
    won: true,
  },
]

export const mockCreatedBets: Bet[] = mockBets.filter((bet) => bet.creator.id === "user-1")
